name: Download Hazm Model

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install huggingface_hub
      - run: python -c "from huggingface_hub import snapshot_download; snapshot_download('roshan-research/hazm-postagger', local_dir='./model/hazm-postagger', local_dir_use_symlinks=False)"
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add model/
          git commit -m "Add model" || echo "No changes"
          git push
