name: Download Model with huggingface_hub

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install huggingface_hub
        run: pip install huggingface_hub
        
      - name: Download model
        run: |
          huggingface-cli download roshan-research/hazm-postagger \
            --local-dir my_downloaded_model \
            --token $HF_TOKEN
      
      # - name: Clone public model
      #   run: |
      #     # فقط برای مدل‌های عمومی که gated: false هستند
      #     git clone https://huggingface.co/roshan-research/hazm-postagger my_downloaded_model
      #     cd my_downloaded_model
      #     git lfs pull
